// Package models defines the data structures used throughout the application.
package entities

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// Task represents a single to-do item in the task manager.
// It includes struct tags to define how the fields are stored in MongoDB (BSON)
// and how they are represented in JSON for API responses.
type Task struct {
	// ID is the unique identifier for the task, generated by MongoDB.
	// `bson:"_id,omitempty"` maps this to the MongoDB `_id` field.
	// `omitempty` tells the driver to omit this field if it's empty.
	// `json:"id,omitempty"` maps this to `id` in JSON for cleaner API output.
	ID primitive.ObjectID `bson:"_id,omitempty" json:"id,omitempty"`

	// Title is a short, descriptive name for the task.
	// `bson:"title"` maps this to the `title` field in MongoDB.
	// `json:"title"` maps this to the `title` field in JSON.
	Title string `bson:"title" json:"title"`

	// Description provides more details about the task.
	Description string `bson:"description" json:"description"`

	// Completed indicates whether the task has been finished.
	Completed bool `bson:"completed" json:"completed"`

	// DueDate is the optional date by which the task should be completed.
	DueDate time.Time `bson:"due_date" json:"due_date"`

	// CreatedAt is the timestamp automatically generated when the task was created.
	CreatedAt time.Time `bson:"created_at" json:"created_at"`
}
